In [1]:
!pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 290.5 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 290.5 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 216.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.5 MB 2.0 MB/s eta 0:00:09
   - -------------------------------------- 0.5/16.5 MB 5.2 MB/s eta 0:00:04
   --- ------------------------------------ 1.2/16.5 MB 8.9 MB/s eta 0:00:02
   ------- -------------------------------- 3.3/16.5 MB 17.5 MB/s eta 0:00:01
   ------------- -------------------------- 5.7/16.5 MB 24.2 MB/s eta 0:00:0

In [15]:
import numpy as np
print("'np.ndim' me dice la dimensión del arreglo")
a1= np.array([1, 2, 3]) #Array de una dimension
a2= np.array([[1, 2, 3],[4, 5, 6]]) #Array de dos dimensiones
a3= np.array([[[1, 2, 3],[4, 5, 6]]]) #Array de tres dimensiones
a3_1= np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]]) #Array de tres dimensiones
a4= np.array([[[[1, 2, 3],[4, 5, 6],[7, 8, 9], [10, 11, 12]]]]) #Array de cuatro dimensiones
print(f"a1 = {a1}")
print(f"El arreglo 'a1' es de {np.ndim(a1)} una sola dimensión")
print()
print(f"a2 = {a2}")
print(f"El arreglo 'a2' es de {np.ndim(a2)} dimensiones")
print()
print(f"a3 = {a3}")
print(f"El arreglo 'a3' es de {np.ndim(a3)} dimensiones")
print()
print(f"a3_1 = {a3}")
print(f"El arreglo 'a3_1' es de {np.ndim(a3_1)} dimensiones")
print()
print(f"a4 = {a4}")
print(f"El arreglo 'a4' es de {np.ndim(a4)} dimensiones")



a1 = [1 2 3]
El arreglo 'a1' es de 1 una sola dimensión

a2 = [[1 2 3]
 [4 5 6]]
El arreglo 'a2' es de 2 dimensiones

a3 = [[[1 2 3]
  [4 5 6]]]
El arreglo 'a3' es de 3 dimensiones

a3_1 = [[[1 2 3]
  [4 5 6]]]
El arreglo 'a3_1' es de 3 dimensiones

a4 = [[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
El arreglo 'a4' es de 4 dimensiones


'ndmin' - Es utilizado en los arreglos para especificar el numero minimo de dimensiones que debe tener, el arrglo no tiene el 'ndmin' especificado entonces se le agragará dimensiones adicionales

In [18]:
import numpy as np
a1= np.array([1, 2, 3]) #Array de una dimension
a1_3= np.array([1, 2, 3], ndmin=3) 

print("Al arreglo 'np.array([1,2,3])' de una dimension se le agregó el parámetro 'ndmin=3' para convertirlo en un arreglo de tres dimensiones")
print()
print(f"a1= {a1}")
print()
print(f"a1_3= {a1_3}")

Al arreglo 'np.array([1,2,3])' de una dimension se le agregó el parámetro 'ndmin=3' para convertirlo en un arreglo de tres dimensiones

a1= [1 2 3]

a1_3= [[[1 2 3]]]


Veamos las funciones:
np.zeros()
np.random.random()
np.arange()

In [44]:
import numpy as np
print("Un 'Shape' define la cantidad de fila y de columnas de un 'array'")
print("np.zeros() ")
print("'np.zeros((5, 3))' incializa un shape() de 5 filas y 3 columnas, con ceros ")
array= np.zeros((5,3))
print(array)
print(f"array.shape= {array.shape}")

Un 'Shape' define la cantidad de fila y de columnas de un 'array'
np.zeros() 
'np.zeros((5, 3))' incializa un shape() de 5 filas y 3 columnas, con ceros 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array.shape= (5, 3) 


np.random.random()- Genera numeros aleatorios entre 'cero' y 'uno'  de un shape()

In [28]:
import numpy as np
print(f"np.random.random((2, 4)) crea un array con un 'shape' de 2 filas y 4 columnas = {np.random.random((2, 4))}")

np.random.random((2, 4)) crea un array con un 'shape' de 2 filas y 4 columnas = [[0.5518871  0.18035944 0.26870658 0.13218897]
 [0.97194708 0.08365399 0.07325865 0.12275158]]


np.arange() se utiliza para generar array con una secuencia de numeros indicadas en el argumento

In [42]:
import numpy as np

a= np.arange(-1,2)
b= np.arange(-3, 3, 1, dtype=int)
c= np.arange(-3, 3, 0.5, dtype=float)

print(f"'np.arange(-1,2)' comienza con '-1' y termina en '2' como no aparece el paso, el valor por defecto es '1' = {a}")
print(f"'np.arange(-3, 3, 1, dtype=int)' comienza con '-3' y termina en '3' con paso '1' y valores 'enteros' = {b}")
print(f"'np.arange(-3, 3, 0.5, dtype=float)' comienza con '-3' y termina en '3' con paso '0.5' y valores 'flotantes' = {c}")



'np.arange(-1,2)' comienza con '-1' y termina en '2' como no aparece el paso, el valor por defecto es '1' = [-1  0  1]
'np.arange(-3, 3, 1, dtype=int)' comienza con '-3' y termina en '3' con paso '1' y valores 'enteros' = [-3 -2 -1  0  1  2]
'np.arange(-3, 3, 0.5, dtype=float)' comienza con '-3' y termina en '3' con paso '0.5' y valores 'flotantes' = [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5]


.flatten() - Sirve para aplanar un array multidimensional

In [53]:
import numpy as np

arreglo= np.array([[[23, 4, 45, 2 ], [3, 34, 4, 1 ], [3, 4, 4, 2 ]]])
print(f"arreglo = {arreglo}")
print(f"dimension = {arreglo.ndim}")

print()
print("Usando la función 'flatten()' podemos aplanar el arreglo: ")
print(f"arreglo.flatten() = {arreglo.flatten()}")
print(f"dimension = {arreglo.flatten().ndim}")

arreglo = [[[23  4 45  2]
  [ 3 34  4  1]
  [ 3  4  4  2]]]
dimension = 3

Usando la función 'flatten()' podemos aplanar el arreglo: 
arreglo.flatten() = [23  4 45  2  3 34  4  1  3  4  4  2]
dimension = 1


reshape() - Pemite cambiar la forma del arreglo sin cambiar sus datos

In [54]:
import numpy as np

import numpy as np

print("arr = np.array([1, 2, 3, 4, 5, 6])")
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print("'reshaped_arr = arr.reshape((2, 3))' cambia el arreglo unidimensional a un arreglo de '2 filas y '3 columnas'")
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# Salida:
# [[1 2 3]
#  [4 5 6]]


arr = np.array([1, 2, 3, 4, 5, 6])
[1 2 3 4 5 6]
'reshaped_arr = arr.reshape((2, 3))' cambia el arreglo unidimensional a un arreglo de '2 filas0 y '3 columnas'
[[1 2 3]
 [4 5 6]]


In [55]:
print("'arr = np.array([[1, 2, 3], [4, 5, 6]])' es un arreglo de '2D'")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("'reshaped_arr = arr.reshape((2, 3, 1)' cambia de '2D' a '3D' lo convierte a dos bloques, cada uno con '3 filas' y '1 columna'")
reshaped_arr = arr.reshape((2, 3, 1))
print(reshaped_arr)


'arr = np.array([[1, 2, 3], [4, 5, 6]])' es un arreglo de '2D'
[[1 2 3]
 [4 5 6]]
'reshaped_arr = arr.reshape((2, 3, 1)' cambia de '2D' a '3D' lo convierte a dos bloques, cada uno con '3 filas' y '1 columna'
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [63]:
print("'arr = np.array([[1, 2, 3], [4, 5, 6]])'")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
print("'reshaped_arr = arr.reshape((3, 2), order='F')'")
reshaped_arr = arr.reshape((3, 2), order='F')
print(reshaped_arr)
print()
print("¿Como lo hizo?")
print("Se genera un arreglo con 'reshape()' de '3' filas y '2' columnas")
print("La orden 'F' toma los dos primeros valores de la primera columna '1 y 4' y para completar")
print("la tercera fila de la primera columna del 'reshape()' coge entonces el primer valor de la segunda columna, es decir, el '2'")
print("con esto ya se creó la primera columna de 'reshape()' con los valores '1, 4, 2'")
print("para la segunda columna de reshape toma entonces el valor siguiente de '2' en la segunda columna, el '5'")
print("y completaria la segunda columna de reshape() con el '3' y el '6' de la tercera columna del arreglo original")

'arr = np.array([[1, 2, 3], [4, 5, 6]])'
[[1 2 3]
 [4 5 6]]

'reshaped_arr = arr.reshape((3, 2), order='F')'
[[1 5]
 [4 3]
 [2 6]]

¿Como lo hizo?
Se genera un arreglo con 'reshape()' de '3' filas y '2' columnas
La orden 'F' toma los dos primeros valores de la primera columna '1 y 4' y para completar
la tercera fila de la primera columna del 'reshape()' coge entonces el primer valor de la segunda columna, es decir, el '2'
con esto ya se creó la primera columna de 'reshape()' con los valores '1, 4, 2'
para la segunda columna de reshape toma entonces el valor siguiente de '2' en la segunda columna, el '5'
y completaria la segunda columna de reshape() con el '3' y el '6' de la tercera columna del arreglo original
